config/routes.rb
MateriaBrasil::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  #match "auth/:provider/callback",      to: "sessions#create"
  #resources :sessions, only: [:new, :destroy]

  resources :materials, only: [:index, :show, :new, :update, :edit, :create] do
    resources :images
    resources :attachments, only: [:edit, :update, :create, :destroy] do
      member do
        get :bookmark
      end
    end
    member do
      put :update_categories
      put :update_attachments
    end
    resources :categories, only: [:index]
    get 'attachments/edit', to: 'materials#edit_attachments', as: :edit_attachments
  end

  resources :manufacturers, only: [:show, :edit, :update]

  #get 'material/:id',                   to: "materials#show",     as: :material
  get 'explore/:category',              to: "materials#explore",  as: :category
  get 'explore/',                       to: "materials#explore",  as: :explore
  #get 'materials',                      to: "materials#index",    as: :materials
  get 'sobre/',                         to: "pages#about",        as: :about
  get 'contato',                        to: "pages#contact",      as: :contact
  #get 'materials/new',                  to: 'materials#new',      as: :new_material
  #get 'categories/new',                 to: 'categories#new',     as: :new_category
  get 'submit/',                        to: "pages#submit",       as: :submit
  get 'portfolio/',                     to: "pages#portfolio",    as: :portfolio
  get 'busca/',                         to: "materials#search",   as: :search
  root                                  to: "materials#index"
end

app/views/partials/_breadcrumb.html.slim
section.breadcrumb
  p.head
    = t "breadcrumb.index.head_html", manufacturer_count: 134, material_count: 574

app/views/partials/_categories.html.slim
.white_box
  h4.materials_count Você buscou por:      
  - path = @category.top_category? ? explore_path : category_path(@category.parent)
  p.filter_history
    - @category.parents.each do | parent |
      = link_to parent.name, category_path(parent)
      br/
    = link_to @category.name, path, class: "link_to_delete"
  span="#{pluralize(@count, 'material ', 'materiais ')} encontrados"

.transparent_box
  h4 Filtrar por:
ul.category
  - @category.top_parent.children.each do |c|
    li.children[class="#{@category.is_activating?(c) ? 'active' : ''}"]
      = link_to c.name, category_path_toggle(@category, c), class: "direct_children"
      - if c.children and @category.is_activating?(c)
        .category_sub_lists
          ul.category_children_list
            - c.children.each do | child |
              li.sub_list_item[class="#{@category.is_activating?(child) ? 'active' : ''}"]
                = link_to child.name, category_path_toggle(@category, child)
                - if child.children.length > 0 and @category.is_activating?(child)
                  ul.category_children_list
                    - child.children.each do | grandchild |
                      li.sub_list_item[class="#{@category.is_activating?(grandchild) ? 'active' : ''}"]
                        = link_to grandchild.name, category_path_toggle(@category, grandchild)
                        - if grandchild.children.length > 0 and @category.is_activating?(grandchild)
                          ul.category_children_list
                            - grandchild.children.each do | grangrandchild |
                              li.sub_list_item[class="#{@category.is_activating?(grangrandchild) ? 'active' : ''}"]
                                = link_to grangrandchild.name, category_path_toggle(@category, grangrandchild)

app/views/partials/_flash.html.slim
- for key, msg in flash
  .flash class="#{key}"
      div class=key
        == msg

app/views/partials/_footer.html.slim
footer#footer
  = image_tag "logo_materia.png", size: "404x26"
  section.code_by
    p
      = t "footer.code_by_html"
      = link_to image_tag("logo_engage.png", size: "109x44"), "http://engage.is"

app/views/partials/_header.html.slim
header.header_menu
  .row
    .large-6.columns
      h1#logo[title="Voltar para a página inicial"]= link_to "MateriaBrasil", root_path
      nav.main_nav
        = link_to t("common.about"), about_path
        = link_to t("common.portfolio"), portfolio_path(anchor: 'design'), id: 'portfolio_link'
        = link_to t("common.contact"), contact_path
    .large-6.columns
      aside.search_account
        .main_actions_nav.left
          = link_to t("common.explore"), explore_path, class: "main_action"
          = link_to t("common.submit"), submit_path, class: "main_action"
        section.search_area
          form.search_form action=search_path
            input[type="text" name="q" value="" placeholder="#{t "common.search_the_site"}" class='field']
        section.account_nav
          - if current_user
            section.user_section
              span.icon.user
              = t "common.my_account"
              span.arrow
                |&#x25BE
              ol.options
                - if current_user.manufacturer
                  li
                    = link_to "Meu perfil", manufacturer_path(current_user.manufacturer)
                - if current_user.manufacturer.try(:materials)
                  li
                    | Meus materiais:
                - current_user.manufacturer.try(:materials).try(:each) do |m|
                  li
                    = link_to m, class: "material-item" do
                      - if m.featured_image.present?
                        = image_tag m.featured_image.image.flat.url, size: "50x41"
                      span= m.name
                li.logout= link_to destroy_user_session_path, method: :delete do
                  span.icon.forward
                  = t('common.logout')
          - else
            = link_to t('common.login_signin'), new_user_session_path(), class: "login-bt"

app/views/partials/_login.html.slim
p= link_to t('common.login_signin'), new_user_session_path(), class: "bt"

app/views/partials/_material_breadcrumb.html.slim
- if position
  aside.white_section.material_breadcrumb
    .list_wrapper
      ol.breadcrumb_list
        li class="#{"current" if position == :descricao}"
          span 01. Descrição
        li class="#{"current" if position == :caracteristicas}"
          span 02. Características
        li class="#{"current" if position == :imagens}"
          span 03. Imagens e anexos
        li class="#{"current" if position == :empresa}"
          span 04. Empresa