config/routes.rb
MateriaBrasil::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  #match "auth/:provider/callback",      to: "sessions#create"
  #resources :sessions, only: [:new, :destroy]

  resources :materials, only: [:index, :show, :new, :update, :edit, :create] do
    resources :images
    resources :attachments, only: [:edit, :update, :create, :destroy] do
      member do
        get :bookmark
      end
    end
    member do
      put :update_categories
      put :update_attachments
    end
    resources :categories, only: [:index]
    get 'attachments/edit', to: 'materials#edit_attachments', as: :edit_attachments
  end

  resources :manufacturers, only: [:show, :edit, :update]

  #get 'material/:id',                   to: "materials#show",     as: :material
  get 'explore/:category',              to: "materials#explore",  as: :category
  get 'explore/',                       to: "materials#explore",  as: :explore
  #get 'materials',                      to: "materials#index",    as: :materials
  get 'sobre/',                         to: "pages#about",        as: :about
  get 'contato',                        to: "pages#contact",      as: :contact
  #get 'materials/new',                  to: 'materials#new',      as: :new_material
  #get 'categories/new',                 to: 'categories#new',     as: :new_category
  get 'submit/',                        to: "pages#submit",       as: :submit
  get 'portfolio/',                     to: "pages#portfolio",    as: :portfolio
  get 'busca/',                         to: "materials#search",   as: :search
  root                                  to: "materials#index"
end

app/models/material.rb
# == Schema Information
#
# Table name: materials
#
#  id                    :integer          not null, primary key
#  resume                :text
#  manufacturer_id       :integer
#  technical_observation :text
#  density               :string(255)
#  dimensions            :string(255)
#  average_price         :string(255)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  name                  :string(255)
#  slug                  :string(255)
#  ncm                   :string(255)
#  certifications        :string(255)
#  awards                :string(255)
#  code                  :string(255)
#  draft                 :boolean          default(TRUE), not null
#

class Material < ActiveRecord::Base
  include PgSearch
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :manufacturer
  has_one :user, through: :manufacturer
  has_many :images, dependent: :destroy
  has_many :attachments, dependent: :destroy
  has_and_belongs_to_many :categories, before_add: :validates_category
  belongs_to :category
  validates :manufacturer, :name, :resume, presence: true
  accepts_nested_attributes_for :images
  accepts_nested_attributes_for :attachments
  attr_accessible :images_attributes, :attachments_attributes, :category_ids, :name, :resume, :dimensions, :density, :average_price, :certifications, :awards, :technical_observation, :category_id, :draft, :manufacturer_id, :code, :ncm

  default_scope order('created_at DESC')

  after_save :check_tree


  pg_search_scope :search_by_name_and_category, against: [:name, :code, :resume], associated_against: {
    categories: [:name, :code_reference],
    manufacturer: [:name]
  }

  scope :approved, where(draft: false)
  scope :pending,  where(draft: true)

  def should_generate_new_friendly_id?
    new_record?
  end

  def sku
    "#{self.code}-#{self.id.to_s.rjust(5,'0')}"
  end

  def categories_string(pid, name = nil)
    if name
      categories.map{|c| c.name if c.parent && c.parent.name == name}.reject{|c| c.nil?}.join(', ')
    elsif pid
      categories.map{|c| c.name if c.parent_id == pid}.reject{|c| c.nil?}.join(', ')
    end
  end

  def has_images?
    images.length > 0
  end

  def published?
    self.draft == false
  end

  def featured_image
    self.images.where(featured: true).first || self.images.first || nil
  end

  def bookmark_image(image_id)
    self.images.each do |img|
      to_bookmark = (img.id == image_id) ? true : false
      img.update_attributes featured: to_bookmark
    end
  end

  private
  def check_tree
    tree = []
    self.categories.each do |cat|
      tree << cat.parents
    end
    self.categories << tree
  end

  def validates_category(category)
     self.categories.delete(category) if self.categories.include? category
  end
end

app/controllers/materials_controller.rb
# coding: utf-8
class MaterialsController < ApplicationController
  inherit_resources
  has_scope :offset
  has_scope :limit, default: 5, only: [:index]
  has_scope :limit, default: 9, only: [:explore]

  include ApplicationHelper

  def index
    @materials  ||= Material.approved.limit(12)
    @partners = [
      {name: "Embraer", img: "embraer.png", url: "http://www.embraer.com/"},
      {name: "Siemens", img: "siemens.png", url: "http://www.respostassustentaveis.com.br/"},
      {name: "Jomo", img: "jomo.png", url: "http://www.jomo-online.com.br/"},
      {name: "GoodYear", img: "goodyear.png", url: "http://www.goodyear.com/"},
      {name: "Santander", img: "santander.png", url: "http://www.santander.com/"},
      {name: "Alstom", img: "alstom.png", url: "http://www.alstom.com/"},
      {name: "Ministério do Desenvolvimento Agrário", img: "mda.png", url: "http://portal.mda.gov.br/portal/"},
      {name: "Bunge", img: "bunge.png", url: "http://www.bunge.com.br/"},
      {name: "GNT", img: "gnt.png", url: "http://gnt.globo.com/"},
      {name: "Jardim Botânico do Rio de Janeiro", img: "jardim_botanico.png", url: "http://www.jbrj.gov.br/"},
      {name: "Studio Arthur Casas", img: "sac.png", url: "http://www.arthurcasas.com/"},
      {name: "Casa Arte & Design", img: "cad.png", url: "http://www.casaartedesign.com.br/index2.php"},
      {name: "Sebrae", img: "sebrae.png", url: "http://www.sebrae.com.br/"},
      {name: "Governo do Rio de Janeiro", img: "gov_rj.png", url: "http://www.rj.gov.br/"},
      {name: "Marin's", img: "marins.png", url: "http://www.marins.net/"},
      {name: "FAPERJ", img: "faperj.png", url: "http://www.faperj.br/"}
    ]
    # return render partial: "blocks" if request.xhr?
  end

  def explore
    if params[:category]
      @category ||= Category.find(params[:category])
      @count = @category.materials.approved.count
      @resource ||= @category.materials.approved.limit(9).offset(params[:offset].to_i)
    else
      @count = Material.approved.count
      @resource ||= Material.approved
    end

    return render(partial: "materials", locals: {materials: @resource}) if request.xhr?
  end

  def search
    if params[:q]
      @resource = Material.search_by_name_and_category(params[:q])
      @count = @resource.count
      return render action: "explore" unless request.xhr?
      return render partial: "materials" if request.xhr?
    end
  end

  def create
    manufacturer = current_user.manufacturer || Manufacturer.create(name: current_user.name, user: current_user)
    @material = Material.new(params[:material])
    authorize @material
    @material.manufacturer = manufacturer
    create! { material_categories_path(@material.id) }
  end

  def edit_attachments
    @material = Material.find(params[:material_id])
    authorize @material
    @material.images.build
    @material.attachments.build
    return render 'edit_attachment'
  end

  def update
    authorize resource
    update! { material_categories_path(@material) }
  end

  def update_categories
    authorize resource
    update! { material_edit_attachments_path(@material) }
  end

  def update_attachments
    authorize resource
    if params[:sent_thru_javascript] == "true"
      update! { material_edit_attachments_path(@material) }
    else
      if @material.images.count > 0
        update! { edit_manufacturer_path(@material.manufacturer) }
      else
        redirect_to  material_edit_attachments_path(@material), alert: 'É necessário adicionar ao menos uma imagem ao produto'
      end
    end
  end

  def new
    @material = Material.new
    authorize @material
  end

  def edit
    authorize resource
    edit!
  end

  def show
    authorize resource
    show!
  end
end

app/helpers/materials_helper.rb
#coding: utf-8
module MaterialsHelper

  def print_row_if_present(val, name)
    if val.present?
      content = ""
      content +=  content_tag(:td, name, class: "faded")
      content +=  content_tag(:td, val)
      content_tag(:tr, content.html_safe)
    end
  end
end

app/views/materials/_blocks.html.slim
= load_block(materials: @materials)

app/views/materials/_characteristics.html.slim
table.char_table
  - val = @material.categories_string(1) rescue nil
  = print_row_if_present(val, "Uso")
  - val = @material.categories_string(73) rescue nil
  = print_row_if_present(val, "Forma")
  - val = @material.categories_string(138) rescue nil
  = print_row_if_present(val, "Visuais")
  - val = @material.categories_string(104) rescue nil
  = print_row_if_present(val, "Táteis")
  - val = @material.categories_string(nil, "Resistência a") rescue nil
  = print_row_if_present(val, "Resistência a")
  - val = @material.categories_string(161) rescue nil
  = print_row_if_present(val, "Processabilidade")
  / - val = @material.categories_string(nil, "Transparência") rescue nil
  / = print_row_if_present(val, "Transparência")
  - val = @material.density rescue nil
  = print_row_if_present(val, "Densidade/gramatura")
  - val = @material.dimensions rescue nil
  = print_row_if_present(val, "Dimensões")
  / - val = @material.packing rescue nil
  / = print_row_if_present(val, "Forma")
  - val = @material.certifications rescue nil
  = print_row_if_present(val, "Normas e certificações")
  - val = @material.awards rescue nil
  = print_row_if_present(val, "Prêmios")
  - @material.attachments.each_with_index do | attc, i |
    = print_row_if_present(link_to(attc.name, attc.file.url, target: :blank), "Anexo #{i+1}")

app/views/materials/_form.html.slim
= simple_form_for @material do |f|
  .form-inputs
    .row
      .large-2.columns
        = f.label :name, "Nome do produto *", class: "required"
      .large-7.columns
        = f.text_field :name, required: "required"
      .large-3.columns.hint
        p Procure usar um nome que explique a composição e uma característica de sustentabilidade relevante do seu produto. Evite nomes comerciais.
    .row
      .large-2.columns
        = f.label :resume, "Descrição do produto *", class: "required"
      .large-7.columns
        = f.text_area :resume, size: "40x10", required: "required"
      .large-3.columns.hint
        p Esse texto será o descritivo. Procure falar das vantagens dele, seus diferenciais de sustentabilidade e outras informações que ajudem as pessoas a entenderem seu processo de fabricação. Procure falar em 2 parágrafos e evite parecer uma propaganda ou algo extremamente técnico. O meio termo é o melhor caminho!
    .row
      .large-2.columns
        = f.label :ncm, "NCM"
      .large-7.columns
        = f.text_field :density
      .large-3.columns.hint
        p NCM significa "Nomenclatura Comum do Mercosul" e trata-se de um código estabelecido pelo Governo Brasileiro para identificar a natureza das mercadorias. A MateriaBrasil precisa desse código para o transporte de amostras e promoção do seu produto.
    .row
      .large-2.columns
        = f.label :dimensions, "Dimensões"
      .large-7.columns
        = f.text_field :dimensions
      .large-3.columns.hint
    .row
      .large-2.columns
        = f.label :density, "Peso ou Densidade ou Gramatura"
      .large-7.columns
        = f.text_field :density
      .large-3.columns.hint
    .row
      .large-2.columns
        = f.label :average_price, "Preço médio"
      .large-7.columns
        = f.text_field :average_price
      .large-3.columns.hint
        p Pode ser uma ordem de grandeza, ou uma faixa de preço. Ex: Aprox. R$ 45,00 o metro quadrado é uma boa frase ;) <br/>Ou A partir de R$ 50,00 o metro quadrado
    .row
      .large-2.columns
        = f.label :certifications, "Normas e certificações"
      .large-7.columns
        = f.text_area :dimensions, size: "40x5"
      .large-3.columns.hint
    .row
      .large-2.columns
        = f.label :awards, "Prêmios"
      .large-7.columns
        = f.text_area :awards, size: "40x5"
      .large-3.columns.hint
    .row
      .large-2.columns
        = f.label :technical_observation, "Informações técnicas importantes"
      .large-7.columns
        = f.text_area :technical_observation, size: "40x10"
      .large-3.columns.hint
        p Aproveite este campo para falar sobre informações técnicas pertinentes ao seu produto, que não se encaixam na pergunta acima.
    hr/
    .row
      .large-12.columns
        = f.button :submit, raw("Próximo passo &#62;"), class: "bt bt_secondary bt_large bt_next"

app/views/materials/_material.html.slim
li.material.fourcol[class="#{'draft' if material.draft}"]
  - if material.has_images?
    .image= link_to image_tag(material.featured_image.image.main.url, title: material.name, alt: material.name), material_path(material)
  - if material.draft
    span.draft_badge Aguardando aprovação
  .name= link_to material.name, material_path(material)

app/views/materials/_materials.html.slim
- materials.each_slice(3) do |material|
  = content_tag(:ol, class: "row materials") do
    = render partial: "materials/material", collection: material

app/views/materials/edit.html.slim
= render partial: "partials/material_breadcrumb", locals: {position: :descricao}
.material_form
  = render 'form'

app/views/materials/edit_attachment.html.slim
= render partial: "partials/material_breadcrumb", locals: {position: :imagens}
.material_form
  = simple_form_for @material, method: :put, url: update_attachments_material_path(@material.id) do |f|
    input type="hidden" name="sent_thru_javascript" id="sent_thru_javascript" value="false"
    .row
      .image-fields.large-12.columns
        .row
          = f.simple_fields_for :images do |img|
            - if img.object.id.present?
              .large-3.columns.img-thumbnail[class="#{'favorite' if img.object == @material.featured_image}"]
                = image_tag(img.object.image.flat.url, class: "uploaded-image") if img.object.image.file.exists?
                = link_to "Remover", material_image_path(resource.id, img.object.id), class: "delete-link", data: { confirm: 'Are you sure?' }, method: :delete
                = link_to "Favoritar", bookmark_material_attachment_path(resource.id, img.object.id), class: "favorite-link"
            - else
              .img-upload
                = img.input :image, label: "<strong>Imagem *</strong>"
    hr/
    .row
      .attachment-fields.large-7.columns
        - i = 0
        = f.simple_fields_for :attachments do |attachment|
          - if attachment.object.id.present?
            .uploaded-attachment
              = link_to attachment.object.name, attachment.object.file.url, class: "uploaded-file-name"
              = attachment.input :name, label: "Alterar nome"
              = link_to "Remover", material_attachment_path(resource.id, attachment.object.id), class: "delete-link", data: { confirm: 'Are you sure?' }, method: :delete
          - else
            .attachment-upload data-index="#{i}"
              = attachment.input :file, label: "Anexos"
              = attachment.input :name, required: false, as: :hidden
          - i += 1
      .large-3.columns.hint
        p Use este espaço para anexar documentos que contenham informações sobre o seu produto, como por exemplo catálogos comerciais, resultados de testes...
    hr/
    .row
      .large-12.columns
        = f.button :submit, raw("Concluir meu cadastro &#62;"), class: "bt bt_secondary bt_large bt_next"

app/views/materials/explore.html.slim
.page.explore
  .white_header_section
    .row
      .large-12.columns
        ul.sub_menu
          - Category.top_level.each do |s|
            li.parents
              = link_to s.name, category_path(s), class: "#{if @category.present? and @category.top_parent == s then 'active' end}"

  .row.materials_exploring
    - if @category.present?
      .large-3.small-3.columns.explore_sidebar
        = render partial: "partials/categories"
      .paginated_materials.large-9.small-9.columns
        = render partial: "materials", locals: {materials: @resource}
    - else
      .paginated_materials.large-12.columns
        = render partial: "materials", locals: {materials: @resource}

app/views/materials/index.html.slim
section.narrow_container.home_info
  h1= t "pages.index.main_call"
  figure.infographic
    section.magenta_circle.top_circle.left_circle
      figcaption= t "pages.index.infographic.magenta.title"
      ul
        li= t "pages.index.infographic.magenta.list.workshops"
        li= t "pages.index.infographic.magenta.list.courses"
        li= t "pages.index.infographic.magenta.list.lectures"
        li= t "pages.index.infographic.magenta.list.expositions"
        li= t "pages.index.infographic.magenta.list.research"
        li= t "pages.index.infographic.magenta.list.content_creation"
        li= t "pages.index.infographic.magenta.list.material_library"
    section.cyan_circle.top_circle.right_circle
      figcaption= t "pages.index.infographic.cyan.title"
      ul
        li= t "pages.index.infographic.cyan.list.product_design"
        li= t "pages.index.infographic.cyan.list.cenography"
        li= t "pages.index.infographic.cyan.list.sustabable_medias"
        li= t "pages.index.infographic.cyan.list.architecture"
        li= t "pages.index.infographic.cyan.list.creative_consulting"
    section.orange_circle.bottom_circle.left_circle
      figcaption= t "pages.index.infographic.orange.title"
      ul
        li= t "pages.index.infographic.orange.list.env_management_system"
        li= t "pages.index.infographic.orange.list.lifecicle_analysis"
        li= t "pages.index.infographic.orange.list.carbon_footprint"
        li= t "pages.index.infographic.orange.list.environmental_labeling"
        li= t "pages.index.infographic.orange.list.materials_specifications"
        li= t "pages.index.infographic.orange.list.technical_consulting"
    section.yellow_circle.bottom_circle.right_circle
      figcaption= t "pages.index.infographic.yellow.title"
      ul
        li= t "pages.index.infographic.yellow.list.business_aceleration"
        li= t "pages.index.infographic.yellow.list.coworking"
        li= t "pages.index.infographic.yellow.list.fablab"

section.materials_wrapper
  .narrow_container
    h1
      = t "pages.index.materials_call"
      br/
      small= t "breadcrumb.index.head_html", material_count: Material.all.size, manufacturer_count: Manufacturer.all.size
    p
      = link_to t("call_to_action.explore_now"), explore_path, class: "bt"
  .materials_preview.row
    - @materials.each do |material|
      - if material.has_images?
        = link_to material_path(material), class: "image_link" do
          = image_tag material.featured_image.image.url(:flat), title: material.name

section.our_partners.medium_container
  h1= t "pages.index.our_partners.call"
  h3= t "pages.index.our_partners.small"
  aside.partners_container
    - @partners.each do |partner|
      = link_to partner[:url], target: "_blank" do
        = image_tag "partners/#{partner[:img]}", title: partner[:name], size: "200x120"

section.download_portfolio.white_section
  .narrow_container
    h1= t "pages.index.want_to_know_portfolio"
    p
      = link_to t("call_to_action.download_portfolio"), "http://www.fibradesign.net/ap_mb.pdf", class: "bt"

app/views/materials/new.html.slim
= render partial: "partials/material_breadcrumb", locals: {position: :descricao}
.material_form
  = render 'form'

app/views/materials/show.html.slim
.material_header.white_header_section
  .row
    .large-12.column
      h1
        = @material.name
      = link_to 'Editar material', edit_material_path(@material), class: "bt bt_primary" if (@material.user != nil && current_user == @material.user) || current_user.try(:email) == ENV['ADMIN_EMAIL'] 
- if !@material.published? && (@material.user != nil && current_user == @material.user)
  .draft_advert.orange_box
    .row
      .large-12.column
        = t "pages.show.draft_advert_html"
section.material.row
  .large-8.small-12.columns
    - unless @material.featured_image.nil?
      .image-slider
        = link_to "+ imagens", "#", class: "more-images-link" if @material.images.size > 1
        .images
          - @material.images.featured_first.each_with_index do | file, index |
            - if file.image.main.url != nil
              = image_tag file.image.main.url, alt: @material.name, class: "slide-image", data: {number: index}
            /- if index > 13
              /- raise file.inspect
    .indicators
      h3
        | Direcionadores de sustentabilidade
      = load_indicators(@material)

    .characteristics.white_box
      h3 Características
      = render partial: "materials/characteristics", locals: { material: @material }

  .large-4.small-12.columns.material_sidebar
    .resume.transparent_box
      p
        = @material.categories_string(nil, "Classes")
        br/
        small.faded= @material.sku
      p= @material.resume
  .large-4.small-12.columns.material_sidebar
    - disponibilidade = @material.categories_string(307) rescue nil
    - local = @material.categories_string(304) rescue nil
    - if disponibilidade.present? || local.present?
      .transparent_box.availability
        - if disponibilidade.present?
          h3 Disponibilidade
          p= @material.categories_string(nil, "Disponibilidade")
        - if local.present? || local.present?
          h3 Local de produção
          p= @material.categories_string(nil, "Local de Produção")

    - if current_user
      .manufacturer.transparent_box
        h3 Contatos comerciais
        table
          tr 
            td.title Fabricante
            td= @material.manufacturer.name
          tr
            td.title Site
            td= link_to @material.manufacturer.site, @material.manufacturer.site, target: '_blank'
        /= simple_form_for "manufacturer", html: {class: "custom"} do |f|
          /= f.input :contact , collection: @material.manufacturer.contacts.publics, label_method: :definition, label: false, prompt: "Selecione um representante"
          /- @material.manufacturer.contacts.publics.each do |contact|
            /table.contact-info id="contact_#{contact.id}" style="display:none"
              /tr 
                /td.title Nome
                /td= contact.name
              /tr 
                /td.title Email
                /td= contact.email
              /tr 
                /td.title Fone
                /td= contact.phone_first
    - else
      .about.transparent_box
        section.data
          h3 Você quer o contato do fornecedor deste material?
          = render partial: 'partials/login'
    
    .share_section.transparent_box
      / Facebook Button
      .fb-like data-href="#{request.original_url}" data-width="250" data-layout="box_count" data-show-faces="false" data-send="false"

      / Twitter Button
      a.twitter-share-button href="https://twitter.com/share" data-url="#{request.original_url}" data-via="MateriaBrasil" data-lang="pt-BR" data-related="anywhereTheJavascriptAPI" data-count="vertical" Tweet
      javascript:
        !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

      / Google Button
      .g-plusone data-size="tall" data-href="#{request.original_url}"
      <script type="text/javascript" src="https://apis.google.com/js/plusone.js">{lang: 'pt-BR'}</script>
  
  .large-12.columns
    .warning
      p
        | As informações exibidas nessa página são fruto de um questionário respondido pelo fabricante.
        br/
        | A MateriaBrasil confia nas respostas que nos são fornecidas. Caso você descubra alguma incoerência, colabore conosco, avisando pelo email 
        = link_to "cadastro@materiabrasil.net", "mailto:cadastro@materiabrasil.net"