config/routes.rb
MateriaBrasil::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  #match "auth/:provider/callback",      to: "sessions#create"
  #resources :sessions, only: [:new, :destroy]

  resources :materials, only: [:index, :show, :new, :update, :edit, :create] do
    resources :images
    resources :attachments, only: [:edit, :update, :create, :destroy] do
      member do
        get :bookmark
      end
    end
    member do
      put :update_categories
      put :update_attachments
    end
    resources :categories, only: [:index]
    get 'attachments/edit', to: 'materials#edit_attachments', as: :edit_attachments
  end

  resources :manufacturers, only: [:show, :edit, :update]

  #get 'material/:id',                   to: "materials#show",     as: :material
  get 'explore/:category',              to: "materials#explore",  as: :category
  get 'explore/',                       to: "materials#explore",  as: :explore
  #get 'materials',                      to: "materials#index",    as: :materials
  get 'sobre/',                         to: "pages#about",        as: :about
  get 'contato',                        to: "pages#contact",      as: :contact
  #get 'materials/new',                  to: 'materials#new',      as: :new_material
  #get 'categories/new',                 to: 'categories#new',     as: :new_category
  get 'submit/',                        to: "pages#submit",       as: :submit
  get 'portfolio/',                     to: "pages#portfolio",    as: :portfolio
  get 'busca/',                         to: "materials#search",   as: :search
  root                                  to: "materials#index"
end

app/models/manufacturer.rb
# == Schema Information
#
# Table name: manufacturers
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  site           :string(255)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  address        :string(255)
#  email          :string(255)
#  cnpj           :string(255)
#  razao_social   :string(255)
#  insc_estadual  :string(255)
#  insc_municipal :string(255)
#  city           :string(255)
#  state          :string(255)
#  cep            :string(255)
#  country        :string(255)
#  mail_address   :string(255)
#  certifications :string(255)
#  user_id        :integer
#  phone          :string(255)
#  image          :string(255)
#  description    :text
#  forum          :boolean
#  forum_mail     :string(255)
#

class Manufacturer < ActiveRecord::Base

  validates_presence_of :name

  belongs_to :user
  has_many :contacts
  has_many :materials

  accepts_nested_attributes_for :contacts, allow_destroy: true

  mount_uploader :image, ManufacturerImageUploader

  before_validation :smart_add_url_protocol

  def formated_address
    [self.address, self.city, self.state, self.country, self.cep].join ', '
  end

protected
  def smart_add_url_protocol
    if self.site.present?
      unless self.site[/\Ahttp:\/\//] || self.site[/\Ahttps:\/\//]
        self.site = "http://#{self.site}"
      end
    end
  end
end

app/controllers/manufacturers_controller.rb
# coding: utf-8
class ManufacturersController < ApplicationController
  inherit_resources

  def show
    @contacts = (current_user and (resource.user == current_user || current_user.email == ENV['ADMIN_EMAIL'])) ? resource.contacts : resource.contacts.publics
    @materials = (current_user and (resource.user == current_user || current_user.email == ENV['ADMIN_EMAIL'])) ? resource.materials : resource.materials.approved
  end

  def edit
    authorize resource
    @manufacturer.contacts.build unless @manufacturer.contacts.any?
    edit!
  end

  def update
    authorize resource
    update!(notice: 'Informações atualizadas com sucesso!') { manufacturer_path(@manufacturer) }
  end
end

app/helpers/manufacturers_helper.rb
#coding: utf-8
module ManufacturersHelper

  def link_to_add_fields(name, f, association, html_class)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: html_class, data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/manufacturers/_contact_fields.html.slim
.contact_container
  .large-12.columns
    h3.contact_title Detalhes do contato
  .large-6.columns
    = f.input :name, label: "Nome"
  .large-6.columns
    = f.input :definition, label: "Descrição"
    small.form-hint Exemplos: Representante Comercial RJ, Resp. Técnico, Atendimento, Loja XXX...
  .large-6.columns
    = f.input :email
  .large-6.columns
    = f.input :phone_first, as: :string, label: "Telefone"
  .large-6.columns
    = f.input :address, label: "Endereço", required: false
  .large-6.columns
    = f.hidden_field :_destroy
    = link_to "Remover contato", "#", class: "remove_fields bt tiny"
  .large-12.columns
    = f.input :public, as: :boolean, label: "Quero que este contato seja público"

app/views/manufacturers/_form.html.slim
.material_form
  = simple_form_for @manufacturer, html: {class: "_custom"} do |f|
    .form-inputs
      .row
        .large-7.columns
          = f.input :name
        .large-3.large-offset-2.columns.hint
          p Esse é o nome que vai aparecer para os usuários da plataforma. Use o nome pelo qual você é conhecido. Evite termos como "Ltda", "SA", etc.
        .large-7.columns
          = f.input :description, required: true
        .large-3.large-offset-2.columns.hint
          p Descreva em 01 parágrafo sua empresa.
        .large-7.columns
          = f.input :site, required: true
        .large-7.columns
          = f.input :certifications
        .large-3.large-offset-2.columns.hint
          p Caso sua empresa seja certificada, conte para gente.
      .row
        hr/
        .large-4.columns
          .img-upload
            = f.input :image
        .large-8.columns.image-input-description
          p.big_paragraph
            - if @manufacturer.image.present?
              = image_tag @manufacturer.image.main.url, class: "manufacturer_thumb"
            | Você terá uma imagem do seu perfil. A recomendação é que essa imagem seja a sua marca!
            br/
            | Preferência: fundo branco com 100 x 100 px
      .row
        hr/
        .large-6.columns
          = f.input :razao_social, required: true
        .large-6.columns
          = f.input :cnpj, required: true
        .large-6.columns
          = f.input :insc_estadual
          small.form-hint Se não for o seu caso, deixe em branco
        .large-6.columns
          = f.input :insc_municipal
          small.form-hint Se não for o seu caso, deixe em branco
        .large-10.columns
          = f.input :address, required: true
        .large-2.columns
          = f.input :cep, required: true
      .row
        .large-4.columns
          = f.input :city, required: true
        .large-2.columns
          = f.input :state, required: true
        .large-4.columns
          = f.input :country, required: true
        .large-2.columns
          = f.input :phone, as: :string, required: true
      .row
        .large-12.columns
          = f.input :has_postal_address
        #postal_address
          .large-10.columns
            = f.input :postal_address
          .large-2.columns
            = f.input :postal_cep
          .large-4.columns
            = f.input :postal_city
          .large-2.columns
            = f.input :postal_state
          .large-4.columns
            = f.input :postal_country
          .large-2.columns
            = f.input :postal_phone, as: :string
        .large-12.columns
          hr/
      .narrow_container
        h2.primary_title Contatos
        p.big_paragraph
          | Você escolhe se quer compartilhar os contatos abaixo com todo mundo ou só com a equipe do MateriaBrasil.
          br/
          | Por exemplo, contatos de representantes comerciais e lojas são bons de serem abertos a todos. Já Responsáveis técnicos é melhor que sejam restritos, e que somente nossa equipe técnica tenha acesso.
      .row
        = f.simple_fields_for :contacts do |builder|
          = render 'contact_fields', f: builder
        .large-3.columns
          = link_to_add_fields "Adicionar novo contato +", f, :contacts, "add_fields bt bt_secondary"
      .row
        hr/
        = f.button :submit, "Concluir cadastro!", class: "bt bt_secondary bt_large bt_next"

app/views/manufacturers/edit.html.slim
= render partial: "partials/material_breadcrumb", locals: {position: :empresa}
= render 'form'

app/views/manufacturers/show.html.slim
.manufacturer.page
  .manufacturer_header.white_header_section
    .row
      .large-12.column
        h1
          = resource.name
        = link_to 'Editar dados', edit_manufacturer_path(resource), class: "bt bt_primary" if (resource.user != nil && current_user == resource.user) || current_user.try(:email) == ENV['ADMIN_EMAIL'] 
        hr/
        dl
          dt Site
          dd= resource.site
          dt Certificações
          dd= resource.certifications
          dt Endereço
          dd= resource.formated_address
          dt Telefone
          dd= resource.phone
        - if @contacts.length > 0
          hr/
          h4 Contatos Adicionais
          - @contacts.each do | contact |
            dl
              dt Nome
              dd= contact.name
              dt Descrição
              dd= contact.definition
              dt Email
              dd= contact.email
              dt Telefone
              dd= contact.phone_first
              dt Endereço
              dd= contact.address

  .paginated_materials.large-12.columns
    = render partial: "materials/materials", locals: {materials: @materials}